name: Build NixOS Configuration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v15
        with:
          name: nixbox-dev
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#nixosConfigurations.<hostname>.config.system.build.toplevel
